version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  redis:
      image: redis:7.0.5-alpine
      hostname: redis
      restart: always
      depends_on:
        - web

  celery:
    build: .
    hostname: celery
    entrypoint: celery
    command: -A torty.celery.app worker
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env.prod
    links:
      - redis
    depends_on:
      - redis
      - web

volumes:
  postgres_data: