# Generated by Django 4.1.7 on 2023-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
