# Generated by Django 4.1.7 on 2023-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_topping_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dekor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='topping/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Декоры',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='topping',
            name='slug',
        ),
    ]
