# Generated by Django 4.1.7 on 2023-03-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_price'),
        ('orders', '0005_orderitem_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping', to='shop.topping', verbose_name='Начинка'),
        ),
    ]
