# Generated by Django 4.1.7 on 2023-03-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_quantity_alter_orderitem_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(max_length=10, verbose_name='Количество'),
        ),
    ]
