# Generated by Django 4.1.7 on 2023-03-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='topping',
            field=models.CharField(default='Уточнить начинку по телефону', max_length=255, verbose_name='Начинка'),
        ),
    ]
